name: Daily AI News Generator

on:
  # Run daily at 8:00 AM UTC (adjust as needed)
  schedule:
    - cron: '0 8 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate AI news page
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
        run: |
          python news_agent.py "artificial intelligence" \
            --articles 10 \
            --output docs/index.html

      - name: Copy latest news to archive
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          cp docs/index.html "docs/archive_${TIMESTAMP}.html"

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update AI news page - $(date +%Y-%m-%d)

          Automated daily news generation for artificial intelligence topics."
            git push
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
